import { useRef, useState } from 'react';

import { motion } from 'framer-motion';
import {
  AlertCircle,
  CheckCircle2,
  FileJson,
  FileUp,
  Loader2,
  RotateCcw,
  ShieldCheck,
  ShieldX,
  Upload,
  X,
} from 'lucide-react';

import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';

type VerificationState = 'idle' | 'verifying' | 'valid' | 'invalid' | 'error';

/** Map ZKP engine claim names to human-readable labels */
const CLAIM_LABELS: Record<string, string> = {
  NAME: 'Name Verification',
  AGE_18_PLUS: 'Age ≥ 18 Verification',
  GENDER: 'Gender Verification',
  DOB: 'Date of Birth Verification',
  STUDENT_NAME: 'Degree Verification',
  RESULT: 'Academic Result Verification',
  GRADE: 'CGPA Verification',
  GRAND_TOTAL: 'Certificate Authenticity',
};

interface FileSlot {
  label: string;
  fieldName: string;
  description: string;
  icon: React.ElementType;
}

const fileSlots: FileSlot[] = [
  {
    label: 'proof.json',
    fieldName: 'proof',
    description: 'The zero-knowledge proof generated by the prover.',
    icon: FileJson,
  },
  {
    label: 'public.json',
    fieldName: 'public',
    description: 'The public inputs used during proof generation.',
    icon: FileJson,
  },
  {
    label: 'verification_key.json',
    fieldName: 'vkey',
    description: 'The verification key from the trusted setup.',
    icon: ShieldCheck,
  },
];

function Panel({
  title,
  description,
  icon: Icon,
  children,
  className = '',
}: {
  title: string;
  description: string;
  icon: React.ElementType;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={cn('rounded-[1.5rem] border border-white/10 bg-white/5 p-6 shadow-[0_18px_70px_rgba(2,6,23,0.35)] backdrop-blur-xl', className)}>
      <div className="mb-5 flex items-start gap-3 border-b border-white/10 pb-4">
        <div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-cyan-400/20 bg-cyan-400/10 text-cyan-200">
          <Icon className="h-5 w-5" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-white">{title}</h3>
          <p className="mt-1 text-sm leading-6 text-slate-400">{description}</p>
        </div>
      </div>
      {children}
    </div>
  );
}

function FileUploadSlot({
  slot,
  file,
  onSelect,
  onClear,
}: {
  slot: FileSlot;
  file: File | null;
  onSelect: (file: File) => void;
  onClear: () => void;
}) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [dragOver, setDragOver] = useState(false);
  const Icon = slot.icon;

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setDragOver(false);
    const droppedFile = e.dataTransfer.files?.[0];
    if (droppedFile) onSelect(droppedFile);
  };

  return (
    <div>
      <input
        ref={inputRef}
        type="file"
        accept=".json"
        className="hidden"
        onChange={(e) => {
          const f = e.target.files?.[0];
          if (f) onSelect(f);
        }}
      />

      {file ? (
        <div className="flex items-center justify-between rounded-[1.25rem] border border-emerald-400/20 bg-emerald-400/10 px-4 py-3">
          <div className="flex items-center gap-3">
            <CheckCircle2 className="h-4 w-4 text-emerald-300" />
            <div>
              <p className="text-sm font-medium text-emerald-100">{slot.label}</p>
              <p className="text-xs text-emerald-200/70">{file.name}</p>
            </div>
          </div>
          <button type="button" onClick={onClear} className="rounded-full p-1 hover:bg-white/10">
            <X className="h-3.5 w-3.5 text-emerald-200" />
          </button>
        </div>
      ) : (
        <div
          className={cn(
            'rounded-[1.25rem] border-2 border-dashed bg-slate-950/30 px-5 py-6 text-center transition-colors',
            dragOver
              ? 'border-cyan-400/50 bg-cyan-400/5'
              : 'border-white/10 hover:border-cyan-400/30 hover:bg-white/5',
          )}
          onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full border border-white/10 bg-white/5 text-cyan-200">
                <Icon className="h-5 w-5" />
              </div>
              <div className="text-left">
                <p className="text-sm font-semibold text-white">{slot.label}</p>
                <p className="text-xs text-slate-400">{slot.description}</p>
              </div>
            </div>
            <Button variant="secondary" size="sm" onClick={() => inputRef.current?.click()}>
              <Upload className="h-3.5 w-3.5" />
              Browse
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

export default function VerifyProof() {
  const [files, setFiles] = useState<Record<string, File | null>>({
    proof: null,
    public: null,
    vkey: null,
  });
  const [verificationState, setVerificationState] = useState<VerificationState>('idle');
  const [verifiedClaims, setVerifiedClaims] = useState<string[]>([]);

  const allFilesSelected = files.proof && files.public && files.vkey;

  const setFile = (field: string, file: File) => {
    setFiles((prev) => ({ ...prev, [field]: file }));
    setVerificationState('idle');
    setVerifiedClaims([]);
  };

  const clearFile = (field: string) => {
    setFiles((prev) => ({ ...prev, [field]: null }));
    setVerificationState('idle');
    setVerifiedClaims([]);
  };

  const reset = () => {
    setFiles({ proof: null, public: null, vkey: null });
    setVerificationState('idle');
    setVerifiedClaims([]);
  };

  const handleVerify = async () => {
    if (!files.proof || !files.public || !files.vkey) return;
    setVerificationState('verifying');

    try {
      const formData = new FormData();
      formData.append('proof', files.proof);
      formData.append('public', files.public);
      formData.append('verificationKey', files.vkey);

      const res = await fetch('http://localhost:3001/api/verify-proof', {
        method: 'POST',
        body: formData,
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        setVerificationState('error');
        return;
      }

      if (data.verified) {
        setVerifiedClaims(data.claims || []);
        setVerificationState('valid');
      } else {
        setVerificationState('invalid');
      }
    } catch (err) {
      console.error(err);
      setVerificationState('error');
    }
  };

  return (
    <div className="space-y-8 pb-20">
      {/* Hero */}
      <section className="max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center gap-2 rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200"
        >
          <span className="h-2 w-2 rounded-full bg-cyan-300" />
          Verifier Workflow
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.05 }}
          className="mt-6 text-4xl font-semibold tracking-tight text-white sm:text-5xl"
        >
          Verify Proof
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mt-4 max-w-3xl text-base leading-8 text-slate-400 sm:text-lg"
        >
          Upload the proof files received from a prover and verify the claims — without ever seeing the original document.
        </motion.p>
      </section>

      {/* ── Section 1: Upload Proof Files ──────────────────────────── */}
      <Panel
        title="Upload Proof Files"
        description="Upload the three files provided by the prover."
        icon={FileUp}
      >
        <div className="space-y-3">
          {fileSlots.map((slot) => (
            <FileUploadSlot
              key={slot.fieldName}
              slot={slot}
              file={files[slot.fieldName]}
              onSelect={(file) => setFile(slot.fieldName, file)}
              onClear={() => clearFile(slot.fieldName)}
            />
          ))}
        </div>

        {!allFilesSelected && (
          <p className="mt-4 text-xs text-slate-500">
            Upload all three files to enable verification.
          </p>
        )}
      </Panel>

      {/* ── Section 2: Verify Proof ────────────────────────────────── */}
      <Panel
        title="Verify Proof"
        description="Run the zero-knowledge verification on the uploaded proof files."
        icon={ShieldCheck}
      >
        <div className="flex flex-wrap gap-3">
          <Button
            disabled={!allFilesSelected || verificationState === 'verifying'}
            onClick={handleVerify}
            className="justify-between"
          >
            {verificationState === 'verifying' ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Verifying…
              </>
            ) : (
              <>
                <ShieldCheck className="h-4 w-4" />
                Verify Proof
              </>
            )}
          </Button>
          <Button variant="outline" onClick={reset} className="justify-between">
            <RotateCcw className="h-4 w-4" />
            Reset
          </Button>
        </div>
      </Panel>

      {/* ── Section 3: Verification Result ─────────────────────────── */}
      <Panel
        title="Verification Result"
        description="The result of the proof verification will appear here."
        icon={verificationState === 'valid' ? CheckCircle2 : verificationState === 'invalid' ? ShieldX : ShieldCheck}
      >
        {verificationState === 'valid' ? (
          <div className="rounded-[1.25rem] border border-emerald-400/20 bg-emerald-400/10 p-5">
            <div className="flex items-start gap-4">
              <div className="mt-1 flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-emerald-400/20 bg-emerald-400/15">
                <CheckCircle2 className="h-5 w-5 text-emerald-300" />
              </div>
              <div>
                <h4 className="text-lg font-semibold text-emerald-100">✓ VALID PROOF</h4>
                <p className="mt-2 text-sm leading-6 text-emerald-200/80">
                  This proof is cryptographically valid.
                </p>
              </div>
            </div>

            {/* Verified Claims */}
            {verifiedClaims.length > 0 && (
              <div className="mt-5 border-t border-emerald-400/15 pt-5">
                <p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300/70">
                  Verified Claims
                </p>
                <div className="space-y-2">
                  {verifiedClaims.map((claim) => (
                    <div
                      key={claim}
                      className="flex items-center gap-2.5 rounded-xl border border-emerald-400/15 bg-emerald-400/5 px-4 py-2.5"
                    >
                      <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-300" />
                      <span className="text-sm font-medium text-emerald-100">
                        {CLAIM_LABELS[claim] ?? claim}
                      </span>
                    </div>
                  ))}
                </div>
                <p className="mt-4 text-xs leading-5 text-emerald-200/60">
                  The selected claims were successfully verified without revealing the original document.
                </p>
              </div>
            )}
          </div>
        ) : verificationState === 'invalid' ? (
          <div className="rounded-[1.25rem] border border-red-400/20 bg-red-400/10 p-5">
            <div className="flex items-start gap-4">
              <div className="mt-1 flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-red-400/20 bg-red-400/15">
                <ShieldX className="h-5 w-5 text-red-300" />
              </div>
              <div>
                <h4 className="text-lg font-semibold text-red-100">✗ INVALID PROOF</h4>
                <p className="mt-2 text-sm leading-6 text-red-200/80">
                  This proof failed cryptographic verification.
                </p>
              </div>
            </div>
          </div>
        ) : verificationState === 'error' ? (
          <div className="flex items-start gap-3 rounded-[1.25rem] border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>An error occurred during verification. Please try again.</span>
          </div>
        ) : (
          <div className="rounded-[1.25rem] border border-white/10 bg-slate-950/40 px-5 py-8 text-center">
            <ShieldCheck className="mx-auto h-10 w-10 text-slate-500" />
            <p className="mt-3 text-sm text-slate-400">
              Awaiting verification
            </p>
            <p className="mt-1 text-xs text-slate-500">
              Upload proof files and click Verify Proof to see the result.
            </p>
          </div>
        )}
      </Panel>
    </div>
  );
}
